# -*- coding: utf-8 -*-
"""Final Python Capstone.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lgzrVrlH-cEVNhNSIBJHjZD-f-_QnsOa

***OTP Validation System
"""

S_email='example1@gmail.com'
R_email='example2@gmail.com'
S_pass='xxxxxxxxx'

#importing required librarys
import random
import smtplib,ssl

global otp  # Global Veriable


# Function to Generate Otp
def generateOtp():
  otp = random.randint(100000, 999999)
  email_Service(otp)
  ValidateOtp(otp)

# Function to send email
def email_Service(otp):
  port = 587
  smtp_server = "smtp.gmail.com"
  Sender_email=S_email
  Receiver_email=R_email
  password=S_pass
  subject='OTP Validation Test'
  body='Your Otp is {}'.format(otp)
  message='Subject:{}\n\n{}'.format(subject,body)
  context = ssl.create_default_context()
  with smtplib.SMTP(smtp_server, port) as server:
    server.ehlo()
    server.starttls(context=context)
    server.ehlo()
    server.login(Sender_email, password)
    server.sendmail(Sender_email, Receiver_email, message)
    print("Email Sent")


# Function to validate Otp
def ValidateOtp(code):
  for i in range(3):
      user = input("Enter Your Otp : ")
      if user == str(code):
        print("Otp is Valid")
        return  # Exits the function gracefully
      elif user == 'Resend':
        generateOtp()
        break  # Exit the loop after generating a new OTP
      elif i==2:
        print("'Retry Again in other Session'")
      else:
        print(f"Otp is Invalid. Retry or enter 'Resend' for another otp. You are on {i + 1} try out of 3")
  print("End of OTP validation process.")

#main
generateOtp()